version: '2'
services:
    devops-ci-cd-pipeline-github-actions: 
        image: khawlarouiss/devops-ci-cd-pipeline-github-actions:latest
        ports:
            - "8082:8082" 
        restart: always