name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      release_mode:
        description: 'Set to true for release builds'
        type: boolean
        required: false
        default: false
  push:
    branches: [ main ]

jobs:
  version:
    runs-on: self-hosted
    outputs:
      version: ${{ steps.set-version.outputs.version }}
      is_snapshot: ${{ steps.set-version.outputs.is_snapshot }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download last snapshot artifact
        uses: actions/download-artifact@v4
        with:
          name: snapshot-info
          path: .

      - name: Set Git user
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Determine version
        id: set-version
        run: |
          chmod +x scripts/version.sh
          if [[ "${{ github.event.inputs.release_mode }}" == "true" ]]; then
            ./scripts/version.sh patch release
            echo "is_snapshot=false" >> $GITHUB_OUTPUT
          else
            ./scripts/version.sh patch snapshot
            echo "is_snapshot=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Upload snapshot artifact
        if: ${{ needs.version.outputs.is_snapshot == 'true' || github.event.inputs.release_mode != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-info
          path: snapshot-version.txt
          
  test:
    needs: version
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven Tests
        run: mvn clean test --no-transfer-progress

  sonar:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=devops-ci-cd-pipeline-github-actions

  package:
    needs: sonar
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Package
        run: mvn clean package --no-transfer-progress
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/*.jar

  docker:
    needs: [version, package]
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: built-jar

      - name: Build & Push Docker image
        run: |
          JAR_FILE=$(ls *.jar | head -n 1)
          VERSION_TAG=${{ needs.version.outputs.version }}
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/devops-ci-cd-pipeline-github-actions
          docker build --build-arg JAR_FILE=$JAR_FILE -t $IMAGE_NAME:$VERSION_TAG .
          docker push $IMAGE_NAME:$VERSION_TAG
          if [[ "$VERSION_TAG" == *SNAPSHOT* ]]; then
            docker tag $IMAGE_NAME:$VERSION_TAG $IMAGE_NAME:latest-snapshot
            docker push $IMAGE_NAME:latest-snapshot
          else
            docker tag $IMAGE_NAME:$VERSION_TAG $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
          fi

      - name: Trigger Deploy to Staging
        if: ${{ needs.version.outputs.is_snapshot == 'true' }}
        uses: lasith-kg/dispatch-workflow@v1
        with:
          dispatch-method: workflow_dispatch
          owner: rouisskhawla
          repo: devops-ci-cd-pipeline-github-actions
          workflow: staging.yml
          ref: main
          workflow-inputs: |
            {
              "version": "${{ needs.version.outputs.version }}",
              "is_snapshot": "true"
            }
          token: ${{ secrets.PAT_GITHUB }}
